export const initialProjects = [
  {
    title: "GPA Analytics",
    subtitle: "Web Application — Academic Analytics",
    images: ["/images/project-01.png"],
    description: "A production-ready academic analytics platform with real-time performance insights and predictive analytics engine.",
    problem: "Students lacked a unified tool to predict exam performance and understand their academic standing. Manual calculations were time-consuming and error-prone.",
    approach: "Built a full-stack web application leveraging modern development tools for rapid iteration. Engineered algorithms to calculate internal marks from assignments, CIE scores, and practicals.",
    result: "Delivered a production-ready academic analytics platform with real-time performance insights and predictive analytics.",
    tags: ["AI", "Web Development", "Academic Analytics", "Python", "Full-Stack"],
    year: "2024",
  },
  {
    title: "Fire Detection Robot",
    subtitle: "Hardware — Robotics & Safety Systems",
    images: ["/images/project-02.png"],
    description: "Fully autonomous robot prototype for fire detection and suppression in hazardous environments.",
    problem: "Manual fire response is slow and dangerous in confined or complex environments. Early detection and response are critical for safety.",
    approach: "Engineered a fully autonomous robot using Arduino microcontroller, flame sensors, DC motors, servo mechanism for directional control, and automated water pump activation.",
    result: "Successfully navigates toward fire sources and autonomously triggers suppression — ready for refinement into production safety systems.",
    tags: ["Arduino", "Robotics", "Embedded Systems", "Sensors", "C++"],
    year: "2024",
  },
  {
    title: "Sound-Activated Control",
    subtitle: "Hardware — Home Automation & IoT",
    images: ["/images/project-03.png"],
    description: "Hands-free home automation system using signal processing for clap detection and relay control.",
    problem: "Traditional physical switches require interaction and don't provide smart home integration. Accessibility is limited for users with mobility constraints.",
    approach: "Designed a microcontroller-based home automation system using sound recognition (clap detection) via microphone, signal processing, and relay circuit control.",
    result: "Created a practical hands-free control system improving accessibility and convenience. Extensible to other smart home applications.",
    tags: ["Microcontroller", "Home Automation", "IoT", "Relay Circuit", "Hardware"],
    year: "2024",
  },
];
