export const config = {
  runtime: 'edge',
};

export default async function handler(req: Request) {
  // 1. Initial debug log
  console.log("GROQ KEY EXISTS:", !!process.env.GROQ_API_KEY);

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  try {
    const { message, projects } = await req.json();
    
    // 2. & 3. Safety check for API key
    const GROQ_API_KEY = process.env.GROQ_API_KEY;
    if (!GROQ_API_KEY) {
      console.error("❌ Missing GROQ_API_KEY environment variable");
      return new Response(JSON.stringify({ reply: "Missing API key in production environment" }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    if (!message) {
      return new Response(JSON.stringify({ error: 'Message is required' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    const systemPrompt = `You are a helpful AI assistant for Bharath Kumar S's portfolio website. 
Your task is to answer questions about his projects based ONLY on the data provided below.

PROJECT DATA:
${JSON.stringify(projects || [], null, 2)}

INSTRUCTIONS:
1. Use ONLY the provided project data. If information is missing, politely say you don't have that information.
2. Be professional, concise, and friendly.
3. Answer ONLY based on the projects list. Do not hallucinate other details.
4. Keep responses under 150 words.`;

    const groqMessages = [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: message }
    ];

    console.log("🚀 Sending request to Groq API...");

    // 4. Fetch call with correct headers
    const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${GROQ_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'llama3-8b-8192',
        messages: groqMessages,
        temperature: 0.7,
        max_tokens: 1024
      })
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error("❌ Groq API error response:", errorData);
      throw new Error(`Groq API returned ${response.status}`);
    }

    const data = await response.json();
    
    // 5. Log full response
    console.log("📥 Groq raw response:", data);
    
    // 6. Extraction
    const reply = data?.choices?.[0]?.message?.content || "No response generated by AI";

    // 7. Return clean Response
    return new Response(JSON.stringify({ reply }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });

  } catch (error: any) {
    console.error('❌ Chat API Exception:', error);
    return new Response(JSON.stringify({ 
      reply: "Something went wrong. Please check if GROQ_API_KEY is set in Vercel settings.",
      error: error.message 
    }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}
